apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  # Clave de cifrado para las conexiones guardadas en Airflow
  AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
  # Conexion a la BD de metadatos de Airflow
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://grupo4:grupo4pass@postgres-service.postgres.svc.cluster.local:5432/airflow_db"
  # Usuario y password del admin de la UI
  AIRFLOW_ADMIN_USER: "admin"
  AIRFLOW_ADMIN_PASSWORD: "admin123"
