apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlflow
type: Opaque
stringData:
  MLFLOW_BACKEND_STORE_URI: "postgresql://grupo4:grupo4pass@postgres-service.postgres.svc.cluster.local:5432/mlflow"
  MLFLOW_DEFAULT_ARTIFACT_ROOT: "s3://mlflow-artifacts/"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service.minio.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
