apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p3-mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Laurasotto/MLOPS_Talleres.git
    targetRevision: main
    path: tercer_proyecto/k8s/mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
