apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: mlops-p2
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-nodeport
  namespace: mlops-p2
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30851
  type: NodePort
