# Dos Services para Streamlit:
# - ClusterIP: comunicación interna
# - NodePort 30851: acceso a la UI desde el navegador → http://localhost:30851

# Service interno
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: mlops-p2
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
---
# Service externo — la interfaz de usuario accesible desde el navegador
apiVersion: v1
kind: Service
metadata:
  name: streamlit-nodeport
  namespace: mlops-p2
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30851  # → http://localhost:30851
  type: NodePort
