apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: mlops-p2
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-nodeport
  namespace: mlops-p2
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  type: NodePort
