FROM python:3.11-slim
WORKDIR /app

RUN pip install --no-cache-dir uv
COPY . /app

RUN uv pip install --system -r requisitos.txt

EXPOSE 8989
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8989"]
