apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlops-p2
data:
  MLFLOW_S3_ENDPOINT_URL: http://minio-service:9000
  MLFLOW_BACKEND_STORE_URI: postgresql://postgres:postgres123@postgres-service:5432/mlops_db
  MLFLOW_ARTIFACT_ROOT: s3://mlflows3/mlflow-artifacts
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  MLFLOW_TRACKING_URI: http://mlflow-service:5000
