apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mlops-p2
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: mlops-p2
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30909
  type: NodePort
