# Dos Services para Prometheus:
# - ClusterIP: para que Grafana se conecte a Prometheus dentro del cluster
# - NodePort 30909: para consultar métricas directamente desde el navegador → http://localhost:30909

# Service interno — Grafana usa "http://prometheus-service:9090" como datasource
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mlops-p2
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
# Service externo — para explorar métricas con PromQL directamente desde el navegador
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: mlops-p2
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30909  # → http://localhost:30909
  type: NodePort
