apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  # ClusterIP significa que solo es accesible dentro del cluster, no desde afuera
  # Otros namespaces se conectan usando: postgres-service.postgres.svc.cluster.local
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
