apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: thomasriverafonseca/p3-streamlit:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: streamlit-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
