apiVersion: v1
kind: Secret
metadata:
  name: streamlit-secret
  namespace: streamlit
type: Opaque
stringData:
  DB_HOST: "postgres-service.postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mlops"
  DB_USER: "grupo4"
  DB_PASS: "grupo4pass"
  FASTAPI_URL: "http://inference-service.inference.svc.cluster.local:8000"
